---
inherit_gem:
  citizens-advice-style:
    - default.yml

require: rubocop-rake

AllCops:
  SuggestExtensions: false
  # Match minimum target version to gemspec
  TargetRubyVersion: 3.2

Style/HashSyntax:
  # We do not necessarily find that Ruby 3.1’s hash value shorthand syntax
  # encourages greater readability so support either style
  EnforcedShorthandSyntax: "either"

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false
