---
name: Continuous Integration

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby_version }}, Rails ${{ matrix.rails_version }}
    strategy:
      matrix:
        # Active Ruby versions (https://endoflife.date/ruby)
        ruby_version: ['3.2', '3.3', '3.4']
        # Active Rails versions (https://endoflife.date/rails)
        rails_version: ['~> 7.1.0', '~> 7.2.0', '~> 8.0.0']
    env:
      RAILS_VERSION: ${{ matrix.rails_version }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
      - run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Run tests
        run: bundle exec rake
